### ISSUE TITLE
No lighting module?

### ISSUE THREAD

**Issue by wangsen1312** [neycyanshi/DDRNet#1]
I just try to run the evaluation code.
but  something wrong happens.
     from lighting import get_lighting, get_H
ImportError: No module named lighting

Any suggestion?

**Comment by cyj907** [comment]
same problem here

**Comment by LizhenWangT** [comment]
Sorry for missing some code, we will update the code soon.

**Comment by cyj907** [comment]
Thx. But several scripts still seem to be missing (the first three lines in .gitignore). Could you please remove the first three lines in .gitignore and allow the three scripts to appear in the repo? It seems impossible to run the training/evaluation bash scripts without those python files.

**Comment by neycyanshi** [comment]
@cyj907 we are improving the lighting module, for now you can run `eval.sh`.

**Comment by wangsen1312** [comment]
@neycyanshi  　Still can not run the eval.sh without the lighting module?

**Comment by wangsen1312** [comment]
@cyj907  yes it works. Thank you

**Comment by neycyanshi** [comment]
works
